# Generated by Django 2.2.16 on 2022-04-07 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220407_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1701, message='Мы собираем отзывы на произведения от XVIII века'), django.core.validators.MaxValueValidator(2022, message='Год не может быть из будущего')]),
        ),
    ]
