# Generated by Django 2.2.16 on 2022-04-07 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220407_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Используйте только буквы, цифры и символ "_"', regex='^[-a-zA-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Используйте только буквы, цифры и символ "_"', regex='^[-a-zA-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Используйте только буквы, цифры и символы:@/./+/-/_', regex='^[\\w.@+-]+\\z)')], verbose_name='Имя пользователя'),
        ),
    ]
