# Generated by Django 2.2.16 on 2022-04-07 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220407_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.TextField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(db_index=True, related_name='titles', to='reviews.Genres'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1701, message='Мы собираем отзывы на произведения от XVIII века'), django.core.validators.MaxValueValidator(2022, message='Год не может быть из будущего')]),
        ),
    ]
